DROP DATABASE IF EXISTS CUBREASIENTOS;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS VISIT;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS DESIGN;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS MATERIAL;
DROP TABLE IF EXISTS COLOR;
DROP TABLE IF EXISTS IMAGES;
DROP TABLE IF EXISTS SUPPLIER;

CREATE DATABASE CUBREASIENTOS;

CREATE TABLE EMPLOYEE(
Employee_Id INT NOT NULL IDENTITY(1,1),
Employee_Name VARCHAR(32) NOT NULL,
Employee_MiddleName VARCHAR(32),
Employee_LastName VARCHAR(32) NOT NULL,
Employee_Password VARCHAR(64) NOT NULL,
Employee_Email VARCHAR(256) NOT NULL,
Employee_Phone VARCHAR(32) NOT NULL,
Employee_Type VARCHAR(32) NOT NULL,
Employee_Status BIT NOT NULL,
PRIMARY KEY(Employee_Id)
);

CREATE TABLE MATERIAL(
Material_Id INT NOT NULL IDENTITY(1,1),
Material_Name VARCHAR(32) NOT NULL,
Material_Status BIT NOT NULL,
PRIMARY KEY(Material_Id)
);

CREATE TABLE IMAGES(
Image_Id INT NOT NULL IDENTITY(1,1),
Image_Content VARBINARY(MAX),
PRIMARY KEY(Image_Id)
);

CREATE TABLE DESIGN(
Design_Id INT NOT NULL IDENTITY(1,1),
<<<<<<< Updated upstream
Design_VehicleId INT NOT NULL,
Design_CentralDesignId INT NOT NULL,
Design_LateralDesignId INT NOT NULL,
=======
Design_Description VARCHAR(MAX) NOT NULL,
Design_MaterialId INT  NOT NULL,
Design_Color VARCHAR(32) NOT NULL,
>>>>>>> Stashed changes
Design_ImageId INT NOT NULL,
Design_Status BIT NOT NULL,
Design_Price FLOAT NOT NULL,
Design_Taxable FLOAT NOT NULL,
Design_Service VARCHAR(32) NOT NULL,
PRIMARY KEY(Design_Id),
<<<<<<< Updated upstream
CONSTRAINT Fk_DVehicle FOREIGN KEY (Design_VehicleId) REFERENCES VEHICLE (Vehicle_Id),
CONSTRAINT FK_DCentralDesign FOREIGN KEY (Design_CentralDesignId) REFERENCES CENTRALDESIGN (CentralDesign_Id),
CONSTRAINT FK_DLateralDesign FOREIGN KEY (Design_LateralDesignId) REFERENCES LATERALDESIGN (LateralDesign_Id),
=======
>>>>>>> Stashed changes
CONSTRAINT Fk_DImage FOREIGN KEY (Design_ImageId) REFERENCES IMAGES (Image_Id),
CONSTRAINT Fk_DMaterial FOREIGN KEY(Design_MaterialId) REFERENCES MATERIAL(Material_Id)
);

CREATE TABLE ORDERS(
Order_Id INT NOT NULL IDENTITY(1,1),
Order_Code VARCHAR(32) NOT NULL,
Order_Date DATETIME NOT NULL,
Order_CustomerName VARCHAR(128) NOT NULL,
Order_CustomerId VARCHAR(32) NOT NULL,
Order_CustomerPhone VARCHAR(32) NOT NULL,
Order_CustomerEmail VARCHAR(256) NOT NULL,
Order_CarBrand VARCHAR(32) NOT NULL,
Order_CarModel VARCHAR(64) NOT NULL,
Order_CarModelYear VARCHAR(4) NOT NULL,
Order_CustomerPlateNumber VARCHAR(32) NOT NULL,
Order_Design INT NOT NULL,
Order_Status BIT NOT NULL,
Order_Embroidery BIT NOT NULL,
Order_Supplier INT,
PRIMARY KEY(Order_Id),
CONSTRAINT FK_OSupplier FOREIGN KEY (Order_Supplier) REFERENCES SUPPLIER(Supplier_Id),
CONSTRAINT Fk_ODesign FOREIGN KEY (Order_Design) REFERENCES DESIGN(Design_Id)
);

CREATE TABLE SUPPLIER(
Supplier_Id INT NOT NULL IDENTITY(1,1),
Supplier_Name VARCHAR(32) NOT NULL,
Supplier_Address VARCHAR(256) NOT NULL,
Supplier_Phone VARCHAR(32) NOT NULL,
Supplier_Email VARCHAR(256) NOT NULL,
Supplier_DateAdded DATETIME,
Supplier_Status BIT NOT NULL,
PRIMARY KEY(Supplier_Id),
);

CREATE TABLE VISIT(
Visit_Id INT NOT NULL IDENTITY(1,1),
Visit_Code VARCHAR(32) NOT NULL,
Visit_OrderId INT NOT NULL,
Visit_EmployeeId INT NOT NULL,
Vist_Type VARCHAR(32) NOT NULL,
Visit_Date DATETIME,
Visit_Status BIT NOT NULL,
PRIMARY KEY(Visit_Id),
CONSTRAINT Fk_VOrder FOREIGN KEY (Visit_OrderId) REFERENCES ORDERS (Order_Id),
CONSTRAINT FK_VEmployee FOREIGN KEY (Visit_EmployeeId) REFERENCES EMPLOYEE (Employee_Id),
);

CREATE TABLE INVOICE(
Invoice_Id INT NOT NULL IDENTITY(1,1),
Invoice_Code VARCHAR(32) NOT NULL,
Invoice_OrderId INT NOT NULL,
Invoice_Total FLOAT,
Invoice_AmountPaid FLOAT,
Invoice_Date DATETIME,
Invoice_CustomerName VARCHAR(128) NOT NULL,
Invoice_CustomerPhone VARCHAR(32) NOT NULL,
Invoice_CustomerEmail VARCHAR(256) NOT NULL,
PRIMARY KEY(Invoice_Id),
CONSTRAINT Fk_IOrder FOREIGN KEY (Invoice_Id) REFERENCES ORDERS (Order_Id),
);