DROP DATABASE IF EXISTS CUBREASIENTOS;

DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS VISIT;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS DESIGN;
DROP TABLE IF EXISTS LATERALDESIGN;
DROP TABLE IF EXISTS CENTRALDESIGN;
DROP TABLE IF EXISTS VEHICLESEAT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS MATERIAL;
DROP TABLE IF EXISTS COLOR;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS SEAT;
DROP TABLE IF EXISTS IMAGES;
DROP TABLE IF EXISTS SUPPLIER;

CREATE DATABASE CUBREASIENTOS;

CREATE TABLE EMPLOYEE(
Employee_Id INT NOT NULL IDENTITY(1,1),
Employee_Name VARCHAR(32) NOT NULL,
Employee_MiddleName VARCHAR(32),
Employee_LastName VARCHAR(32) NOT NULL,
Employee_Password VARCHAR(64) NOT NULL,
Employee_Email VARCHAR(256) NOT NULL,
Employee_Phone VARCHAR(32) NOT NULL,
Employee_Type VARCHAR(32) NOT NULL,
Employee_Status BIT NOT NULL,
PRIMARY KEY(Employee_Id)
);

CREATE TABLE MATERIAL(
Material_Id INT NOT NULL IDENTITY(1,1),
Material_Name VARCHAR(32) NOT NULL,
Material_Status BIT NOT NULL,
PRIMARY KEY(Material_Id)
);

CREATE TABLE COLOR(
Color_Id INT NOT NULL IDENTITY(1,1),
Color_Name VARCHAR(32) NOT NULL,
PRIMARY KEY(Color_Id)
);

CREATE TABLE VEHICLE(
Vehicle_Id INT NOT NULL IDENTITY(1,1),
Vehicle_Brand VARCHAR(32) NOT NULL,
Vehicle_Model VARCHAR(64) NOT NULL,
Vehicle_ModelYear INT NOT NULL,
PRIMARY KEY(Vehicle_Id)
);

CREATE TABLE SEAT(
Seat_Id INT NOT NULL IDENTITY(1,1),
Seat_Description VARCHAR(256) NOT NULL,
PRIMARY KEY(Seat_Id)
);

CREATE TABLE VEHICLESEAT(
VehicleSeat_Id INT NOT NULL IDENTITY(1,1),
VehicleSeat_VehicleId INT NOT NULL,
VehicleSeat_SeatId INT NOT NULL,
VehicleSeat_Price FLOAT NOT NULL,
VehicleSeat_Taxable FLOAT NOT NULL
PRIMARY KEY(VehicleSeat_Id)
CONSTRAINT Fk_VSVehicle FOREIGN KEY (VehicleSeat_VehicleId) REFERENCES VEHICLE (Vehicle_Id),
CONSTRAINT Fk_VSSeat FOREIGN KEY (VehicleSeat_SeatId) REFERENCES SEAT (Seat_Id)
);

CREATE TABLE LATERALDESIGN(
LateralDesign_Id INT NOT NULL IDENTITY(1,1),
LateralDesign_MaterialId INT NOT NULL,
LateralDesign_ColorId INT NOT NULL,
PRIMARY KEY(LateralDesign_Id),
CONSTRAINT FK_LDMaterial FOREIGN KEY (LateralDesign_MaterialId) REFERENCES MATERIAL (Material_Id),
CONSTRAINT FK_LDColor FOREIGN KEY (LateralDesign_ColorId) REFERENCES COLOR (Color_Id)
);

CREATE TABLE CENTRALDESIGN(
CentralDesign_Id INT NOT NULL IDENTITY(1,1),
CentralDesign_MaterialId INT NOT NULL,
CentralDesign_ColorId INT NOT NULL,
PRIMARY KEY(CentralDesign_Id),
CONSTRAINT FK_CDMaterial FOREIGN KEY (CentralDesign_MaterialId) REFERENCES MATERIAL (Material_Id),
CONSTRAINT FK_CDColor FOREIGN KEY (CentralDesign_ColorId) REFERENCES COLOR (Color_Id)
);

CREATE TABLE IMAGES(
Image_Id INT NOT NULL IDENTITY(1,1),
Image_Content VARBINARY(MAX),
PRIMARY KEY(Image_Id)
);

CREATE TABLE DESIGN(
Design_Id INT NOT NULL IDENTITY(1,1),
Design_VehicleSeatId INT NOT NULL,
Design_CentralDesignId INT NOT NULL,
Design_LateralDesignId INT NOT NULL,
Design_ImageId INT NOT NULL,
Design_Status BIT NOT NULL,
PRIMARY KEY(Design_Id),
CONSTRAINT Fk_DVehicleSeat FOREIGN KEY (Design_VehicleSeatId) REFERENCES VEHICLESEAT (VehicleSeat_Id),
CONSTRAINT FK_DCentralDesign FOREIGN KEY (Design_CentralDesignId) REFERENCES CENTRALDESIGN (CentralDesign_Id),
CONSTRAINT FK_DLateralDesign FOREIGN KEY (Design_LateralDesignId) REFERENCES LATERALDESIGN (LateralDesign_Id),
CONSTRAINT Fk_DImage FOREIGN KEY (Design_ImageId) REFERENCES IMAGES (Image_Id),
);

CREATE TABLE ORDERS(
Order_Id INT NOT NULL IDENTITY(1,1),
Order_Code VARCHAR(32) NOT NULL,
Order_Date DATETIME NOT NULL,
Order_CustomerName VARCHAR(128) NOT NULL,
Order_CustomerId VARCHAR(32) NOT NULL,
Order_CustomerPhone VARCHAR(32) NOT NULL,
Order_CustomerEmail VARCHAR(256) NOT NULL,
Order_CustomerCar INT NOT NULL,
Order_CustomerPlateNumber VARCHAR(32) NOT NULL,
Order_FirstVisitDate DATETIME,
Order_SecondVisitDate DATETIME,
Order_Status BIT NOT NULL,
PRIMARY KEY(Order_Id),
CONSTRAINT Fk_OCustomerCar FOREIGN KEY (Order_CustomerCar) REFERENCES VEHICLE (Vehicle_Id),
);

CREATE TABLE SUPPLIER(
Supplier_Id INT NOT NULL IDENTITY(1,1),
Supplier_Name VARCHAR(32) NOT NULL,
Supplier_Address VARCHAR(256) NOT NULL,
Supplier_Phone VARCHAR(32) NOT NULL,
Supplier_Email VARCHAR(256) NOT NULL,
Supplier_DateAdded DATETIME,
Supplier_Status BIT NOT NULL,
PRIMARY KEY(Supplier_Id),
);

CREATE TABLE PRODUCT(
Product_Id INT NOT NULL IDENTITY(1,1),
Product_OrderId INT NOT NULL,
Product_DesignId INT NOT NULL,
Product_SupplierId INT NOT NULL,
Product_Embroidery BIT NOT NULL,
PRIMARY KEY(Product_Id),
CONSTRAINT Fk_POrder FOREIGN KEY (Product_OrderId) REFERENCES ORDERS (Order_Id),
CONSTRAINT FK_PDesign FOREIGN KEY (Product_DesignId) REFERENCES DESIGN (Design_Id),
CONSTRAINT FK_PSupplier FOREIGN KEY (Product_SupplierId) REFERENCES SUPPLIER (Supplier_Id),
);

CREATE TABLE VISIT(
Visit_Id INT NOT NULL IDENTITY(1,1),
Visit_Code VARCHAR(32) NOT NULL,
Visit_OrderId INT NOT NULL,
Visit_EmployeeId INT NOT NULL,
Visit_Type VARCHAR(32) NOT NULL,
Visit_Date DATETIME,
Visit_Status BIT NOT NULL,
PRIMARY KEY(Visit_Id),
CONSTRAINT Fk_VOrder FOREIGN KEY (Visit_OrderId) REFERENCES ORDERS (Order_Id),
CONSTRAINT FK_VEmployee FOREIGN KEY (Visit_EmployeeId) REFERENCES EMPLOYEE (Employee_Id),
);

CREATE TABLE INVOICE(
Invoice_Id INT NOT NULL IDENTITY(1,1),
Invoice_Code VARCHAR(32) NOT NULL,
Invoice_OrderId INT NOT NULL,
Invoice_Total FLOAT,
Invoice_Date DATETIME,
PRIMARY KEY(Invoice_Id),
CONSTRAINT Fk_IOrder FOREIGN KEY (Invoice_Id) REFERENCES ORDERS (Order_Id),
);
